In [3]:
import pandas as pd
from qiskit import QuantumCircuit
from pathlib import Path

rows = []

for file in Path("../benchmarks").glob("*.qasm"):

    qc = QuantumCircuit.from_qasm_file(str(file))

    rows.append({
        "circuit": file.stem,
        "qubits": qc.num_qubits,
        "depth": qc.depth(),
        "gates": len(qc.data),
        "two_qubit_gates": qc.num_nonlocal_gates()
    })

df = pd.DataFrame(rows)

display(df)

df.to_csv(
    "../results/circuit_stats.csv",
    index=False
)

   circuit  qubits  depth  gates  two_qubit_gates
0   qft_10      10     75    261              105
1  qaoa_20      20     48    244              184
2   qft_20      20    155   1021              410
3  qaoa_10      10     26     82               52

In [2]:
import pandas as pd
from qiskit import QuantumCircuit
from pathlib import Path

rows = []

for file in Path("../benchmarks/vqe").glob("*.qasm"):

    qc = QuantumCircuit.from_qasm_file(str(file))

    rows.append({
        "circuit": file.stem,
        "qubits": qc.num_qubits,
        "depth": qc.depth(),
        "gates": len(qc.data),
        "two_qubit_gates": qc.num_nonlocal_gates()
    })

df = pd.DataFrame(rows)

display(df)

df.to_csv(
    "../results/circuit_stats.csv",
    index=False
)

            circuit  qubits  depth  gates  two_qubit_gates
0  vqe_two_local_20      20     82    671              570
1   vqe_real_amp_10      10     18     78               27
2   vqe_real_amp_20      20     28    158               57
3  vqe_two_local_10      10     42    186              135